parameters:
    # Database parameters
    database_host: postgres
    database_port: '%env(POSTGRES_PORT)%'
    database_name: '%env(POSTGRES_DB)%'
    database_user: '%env(POSTGRES_USER)%'
    database_password: '%env(POSTGRES_PASSWORD)%'

    # Mailer parameters
    mailer_transport: %env(SMTP_TRANSPORT)%
    mailer_host: '%env(SMTP_HOST)%'
    mailer_user: '%env(SMTP_USER)%'
    mailer_password: '%env(SMTP_PASSWORD)%'

    # Secret
    secret: '%env(SECRET)%'

    # Redis parameters
    redis_dsn: '%env(REDIS_DSN)%'
    redis_options: ~
    session_ttl: 86400
